// Generated from banque-produits-prix-2026-09-29.md by scripts/generate-price-seed.py.
// Review the Markdown before regenerating. These are indicative prices, not live offers.
export interface PriceSeedRow { scope: 'bank' | 'catalogue'; name: string; eurPerKg: number; confidence: 'faible' | 'moyenne' | 'forte' }
export const PRICE_SEED_DATE = '2026-09-29';
export const PRICE_SEED: PriceSeedRow[] = [
  { scope: "bank", name: "Melon", eurPerKg: 3.4, confidence: "faible" },
  { scope: "bank", name: "Framboise", eurPerKg: 24.72, confidence: "moyenne" },
  { scope: "bank", name: "Orange", eurPerKg: 2.07, confidence: "moyenne" },
  { scope: "bank", name: "Avocat", eurPerKg: 9.93, confidence: "faible" },
  { scope: "bank", name: "Banane", eurPerKg: 1.99, confidence: "moyenne" },
  { scope: "bank", name: "Abricot", eurPerKg: 7.5, confidence: "faible" },
  { scope: "bank", name: "Kiwi", eurPerKg: 9.2, confidence: "faible" },
  { scope: "bank", name: "Cerise", eurPerKg: 15.53, confidence: "faible" },
  { scope: "bank", name: "Past\u00e8que", eurPerKg: 1.5, confidence: "faible" },
  { scope: "bank", name: "P\u00eache", eurPerKg: 3.0, confidence: "moyenne" },
  { scope: "bank", name: "Pamplemousse", eurPerKg: 2.63, confidence: "faible" },
  { scope: "bank", name: "Fraise", eurPerKg: 10.0, confidence: "moyenne" },
  { scope: "bank", name: "kiwi jaune", eurPerKg: 6.9, confidence: "faible" },
  { scope: "bank", name: "m\u00e9lange de fruits rouges surgel\u00e9s", eurPerKg: 11.65, confidence: "moyenne" },
  { scope: "bank", name: "mirabelle", eurPerKg: 6.77, confidence: "moyenne" },
  { scope: "bank", name: "myrtille", eurPerKg: 23.0, confidence: "moyenne" },
  { scope: "bank", name: "m\u00fbre", eurPerKg: 29.52, confidence: "faible" },
  { scope: "bank", name: "cassis", eurPerKg: 10.0, confidence: "faible" },
  { scope: "bank", name: "Raisin", eurPerKg: 4.67, confidence: "moyenne" },
  { scope: "bank", name: "Mangue", eurPerKg: 6.63, confidence: "faible" },
  { scope: "bank", name: "Prune", eurPerKg: 9.98, confidence: "moyenne" },
  { scope: "bank", name: "myrtilles sauvages surgel\u00e9es", eurPerKg: 19.97, confidence: "moyenne" },
  { scope: "bank", name: "olives", eurPerKg: 8.06, confidence: "moyenne" },
  { scope: "bank", name: "M\u00e2che, crue", eurPerKg: 7.99, confidence: "moyenne" },
  { scope: "bank", name: "Batavia, crue", eurPerKg: 5.76, confidence: "faible" },
  { scope: "bank", name: "Carotte", eurPerKg: 1.94, confidence: "moyenne" },
  { scope: "bank", name: "Ma\u00efs (bo\u00eete)", eurPerKg: 4.3, confidence: "moyenne" },
  { scope: "bank", name: "Tomate", eurPerKg: 4.5, confidence: "moyenne" },
  { scope: "bank", name: "Poivron rouge", eurPerKg: 4.5, confidence: "faible" },
  { scope: "bank", name: "Oignon", eurPerKg: 2.82, confidence: "moyenne" },
  { scope: "bank", name: "Courgette (cuite)", eurPerKg: 3.08, confidence: "faible" },
  { scope: "bank", name: "Laitue, crue", eurPerKg: 5.76, confidence: "faible" },
  { scope: "bank", name: "Concombre", eurPerKg: 3.36, confidence: "faible" },
  { scope: "bank", name: "Patate douce (cuite)", eurPerKg: 4.0, confidence: "moyenne" },
  { scope: "bank", name: "Petits pois (cuits)", eurPerKg: 2.5, confidence: "moyenne" },
  { scope: "bank", name: "Haricots verts (cuits)", eurPerKg: 2.49, confidence: "moyenne" },
  { scope: "bank", name: "ail", eurPerKg: 11.16, confidence: "moyenne" },
  { scope: "bank", name: "lentilles vertes en bo\u00eete", eurPerKg: 3.34, confidence: "moyenne" },
  { scope: "bank", name: "petits pois en conserve \u00e9goutt\u00e9s", eurPerKg: 4.12, confidence: "moyenne" },
  { scope: "bank", name: "Brocoli (cuit)", eurPerKg: 2.6, confidence: "moyenne" },
  { scope: "bank", name: "radis", eurPerKg: 6.36, confidence: "faible" },
  { scope: "bank", name: "Pain complet", eurPerKg: 2.23, confidence: "moyenne" },
  { scope: "bank", name: "Pommes de terre saut\u00e9es", eurPerKg: 5.58, confidence: "moyenne" },
  { scope: "bank", name: "P\u00e2tes (cuites)", eurPerKg: 0.97, confidence: "faible" },
  { scope: "bank", name: "Pain baguette", eurPerKg: 4.8, confidence: "moyenne" },
  { scope: "bank", name: "Frites", eurPerKg: 1.64, confidence: "moyenne" },
  { scope: "bank", name: "Riz blanc (cuit)", eurPerKg: 1.0, confidence: "faible" },
  { scope: "bank", name: "Pomme de terre (cuite \u00e0 l'eau)", eurPerKg: 1.5, confidence: "moyenne" },
  { scope: "bank", name: "Semoule (cuite)", eurPerKg: 0.52, confidence: "faible" },
  { scope: "bank", name: "Lentilles (cuites)", eurPerKg: 1.4, confidence: "faible" },
  { scope: "bank", name: "pain de mie complet", eurPerKg: 2.24, confidence: "moyenne" },
  { scope: "bank", name: "ma\u00efs", eurPerKg: 3.23, confidence: "moyenne" },
  { scope: "bank", name: "ma\u00efs en conserve", eurPerKg: 4.4, confidence: "moyenne" },
  { scope: "bank", name: "pain de mie", eurPerKg: 2.5, confidence: "moyenne" },
  { scope: "bank", name: "p\u00e2tes bio granoro", eurPerKg: 3.98, confidence: "moyenne" },
  { scope: "bank", name: "p\u00e2tes compl\u00e8tes", eurPerKg: 2.23, confidence: "moyenne" },
  { scope: "bank", name: "lentilles corail cuites", eurPerKg: 2.34, confidence: "faible" },
  { scope: "bank", name: "pommes de terre saut\u00e9es \u00e0 l'huile de tournesol", eurPerKg: 5.58, confidence: "moyenne" },
  { scope: "bank", name: "pommes de terre en cubes surgel\u00e9es", eurPerKg: 4.18, confidence: "faible" },
  { scope: "bank", name: "Steak hach\u00e9 5% (cuit)", eurPerKg: 28.3, confidence: "moyenne" },
  { scope: "bank", name: "Steak hach\u00e9 15% (cuit)", eurPerKg: 20.5, confidence: "moyenne" },
  { scope: "bank", name: "Cuisse de poulet (cuite)", eurPerKg: 8.0, confidence: "faible" },
  { scope: "bank", name: "Lardons (cuits)", eurPerKg: 12.33, confidence: "faible" },
  { scope: "bank", name: "Filet de poulet (cuit)", eurPerKg: 15.5, confidence: "moyenne" },
  { scope: "bank", name: "Aile de poulet (cuite)", eurPerKg: 26.76, confidence: "faible" },
  { scope: "bank", name: "Jambon blanc", eurPerKg: 14.8, confidence: "moyenne" },
  { scope: "bank", name: "p\u00e2t\u00e9 porc canard et foie gras", eurPerKg: 18.0, confidence: "faible" },
  { scope: "bank", name: "jambon cru", eurPerKg: 30.67, confidence: "moyenne" },
  { scope: "bank", name: "c\u00f4te de porc", eurPerKg: 8.55, confidence: "moyenne" },
  { scope: "bank", name: "viande de boeuf brais\u00e9e", eurPerKg: 22.0, confidence: "faible" },
  { scope: "bank", name: "confit de canard", eurPerKg: 25.09, confidence: "faible" },
  { scope: "bank", name: "filet de dinde", eurPerKg: 13.92, confidence: "moyenne" },
  { scope: "bank", name: "steak hach\u00e9 de b\u0153uf", eurPerKg: 20.12, confidence: "moyenne" },
  { scope: "bank", name: "boulette de viande industrielle", eurPerKg: 15.34, confidence: "moyenne" },
  { scope: "bank", name: "escalope de volaille", eurPerKg: 22.0, confidence: "faible" },
  { scope: "bank", name: "magret de canard, chair sans peau", eurPerKg: 24.0, confidence: "faible" },
  { scope: "bank", name: "peau et gras de canard", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "aiguillettes de poulet marin\u00e9es", eurPerKg: 13.74, confidence: "moyenne" },
  { scope: "bank", name: "Entrec\u00f4te de b\u0153uf (cuite)", eurPerKg: 37.0, confidence: "faible" },
  { scope: "bank", name: "Saucisson sec", eurPerKg: 17.2, confidence: "moyenne" },
  { scope: "bank", name: "viande des Grisons", eurPerKg: 57.84, confidence: "moyenne" },
  { scope: "bank", name: "morceaux de poulet cuit", eurPerKg: 16.83, confidence: "faible" },
  { scope: "bank", name: "peau", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "pilon de poulet, chair sans peau", eurPerKg: 9.68, confidence: "faible" },
  { scope: "bank", name: "peau de poulet", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "g\u00e9siers de volaille", eurPerKg: 10.77, confidence: "moyenne" },
  { scope: "bank", name: "cuisse de poulet, chair sans peau", eurPerKg: 9.27, confidence: "faible" },
  { scope: "bank", name: "Sardines en bo\u00eete (huile)", eurPerKg: 13.38, confidence: "moyenne" },
  { scope: "bank", name: "Saumon (cuit)", eurPerKg: 39.0, confidence: "faible" },
  { scope: "bank", name: "Thon en bo\u00eete (au naturel)", eurPerKg: 14.0, confidence: "moyenne" },
  { scope: "bank", name: "anchois", eurPerKg: 38.2, confidence: "moyenne" },
  { scope: "bank", name: "Emmental", eurPerKg: 8.08, confidence: "moyenne" },
  { scope: "bank", name: "Fromage blanc 3%", eurPerKg: 2.63, confidence: "moyenne" },
  { scope: "bank", name: "\u0152uf (entier)", eurPerKg: 8.5, confidence: "faible" },
  { scope: "bank", name: "Fromage blanc 0%", eurPerKg: 2.44, confidence: "moyenne" },
  { scope: "bank", name: "Skyr", eurPerKg: 5.03, confidence: "moyenne" },
  { scope: "bank", name: "Mozzarella", eurPerKg: 7.44, confidence: "moyenne" },
  { scope: "bank", name: "cottage cheese", eurPerKg: 11.38, confidence: "moyenne" },
  { scope: "bank", name: "Isey skyr", eurPerKg: 8.9, confidence: "moyenne" },
  { scope: "bank", name: "Chocolat noir 70%", eurPerKg: 27.6, confidence: "forte" },
  { scope: "bank", name: "Chocolat au lait", eurPerKg: 23.37, confidence: "moyenne" },
  { scope: "bank", name: "Chocolat noir 85%", eurPerKg: 26.9, confidence: "moyenne" },
  { scope: "bank", name: "Glace (cr\u00e8me glac\u00e9e)", eurPerKg: 3.2, confidence: "moyenne" },
  { scope: "bank", name: "Sucre", eurPerKg: 0.79, confidence: "moyenne" },
  { scope: "bank", name: "Chips", eurPerKg: 5.4, confidence: "moyenne" },
  { scope: "bank", name: "glace cornet vanille pralin\u00e9", eurPerKg: 5.4, confidence: "moyenne" },
  { scope: "bank", name: "pop-corn sucr\u00e9", eurPerKg: 11.67, confidence: "moyenne" },
  { scope: "bank", name: "cornet de glace Extr\u00eame vanille", eurPerKg: 7.2, confidence: "moyenne" },
  { scope: "bank", name: "Huile d'olive", eurPerKg: 10.21, confidence: "moyenne" },
  { scope: "bank", name: "Noisettes", eurPerKg: 32.98, confidence: "faible" },
  { scope: "bank", name: "huile de tournesol", eurPerKg: 2.65, confidence: "moyenne" },
  { scope: "bank", name: "huile de lin", eurPerKg: 6.21, confidence: "faible" },
  { scope: "bank", name: "graine de lin", eurPerKg: 13.64, confidence: "faible" },
  { scope: "bank", name: "huile de noix", eurPerKg: 20.63, confidence: "moyenne" },
  { scope: "bank", name: "Amandes", eurPerKg: 16.56, confidence: "moyenne" },
  { scope: "bank", name: "mayonnaise", eurPerKg: 6.84, confidence: "moyenne" },
  { scope: "bank", name: "tapenade verte", eurPerKg: 13.63, confidence: "moyenne" },
  { scope: "bank", name: "Beurre", eurPerKg: 10.6, confidence: "moyenne" },
  { scope: "bank", name: "Coca-Cola Zero", eurPerKg: 1.24, confidence: "moyenne" },
  { scope: "bank", name: "Jus d'orange", eurPerKg: 2.11, confidence: "moyenne" },
  { scope: "bank", name: "Vin rouge", eurPerKg: 4.32, confidence: "moyenne" },
  { scope: "bank", name: "Limonade", eurPerKg: 0.69, confidence: "moyenne" },
  { scope: "bank", name: "cidre 5% vol", eurPerKg: 2.79, confidence: "moyenne" },
  { scope: "bank", name: "Fuze Tea", eurPerKg: 1.12, confidence: "moyenne" },
  { scope: "bank", name: "Hypro danone", eurPerKg: 6.0, confidence: "faible" },
  { scope: "bank", name: "poulet parmigiana", eurPerKg: 14.0, confidence: "faible" },
  { scope: "bank", name: "pan con tomate", eurPerKg: 7.0, confidence: "faible" },
  { scope: "bank", name: "pizza l\u00e9gumes pesto Parmigiano Reggiano", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "Pizza margherita", eurPerKg: 10.36, confidence: "moyenne" },
  { scope: "bank", name: "burger au poulet", eurPerKg: 19.0, confidence: "faible" },
  { scope: "bank", name: "dhal de lentilles corail", eurPerKg: 5.0, confidence: "faible" },
  { scope: "bank", name: "pommes de terre grenailles avec mati\u00e8re grasse", eurPerKg: 5.0, confidence: "faible" },
  { scope: "bank", name: "pizza merguez et viande hach\u00e9e", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "pizza au ch\u00e8vre", eurPerKg: 7.22, confidence: "moyenne" },
  { scope: "bank", name: "caviar d\u2019aubergine", eurPerKg: 14.57, confidence: "moyenne" },
  { scope: "bank", name: "rillettes de thon", eurPerKg: 14.0, confidence: "moyenne" },
  { scope: "bank", name: "Sel", eurPerKg: 1.82, confidence: "moyenne" },
  { scope: "bank", name: "Magn\u00e9sium (compl\u00e9ment)", eurPerKg: 95.0, confidence: "faible" },
  { scope: "bank", name: "Collag\u00e8ne en peptides (poudre)", eurPerKg: 60.0, confidence: "faible" },
  { scope: "bank", name: "Prot\u00e9ine en poudre (whey)", eurPerKg: 28.0, confidence: "faible" },
  { scope: "bank", name: "Cr\u00e9atine (monohydrate)", eurPerKg: 30.0, confidence: "faible" },
  { scope: "bank", name: "Vitamine C (compl\u00e9ment)", eurPerKg: 80.0, confidence: "faible" },
  { scope: "bank", name: "curcuma", eurPerKg: 14.0, confidence: "faible" },
  { scope: "bank", name: "compl\u00e9ment multivitamines et min\u00e9raux", eurPerKg: 125.0, confidence: "faible" },
  { scope: "bank", name: "Om\u00e9ga 3 Nutripure", eurPerKg: 287.78, confidence: "faible" },
  { scope: "bank", name: "Vinaigre balsamique", eurPerKg: 6.68, confidence: "moyenne" },
  { scope: "bank", name: "Ketchup", eurPerKg: 2.25, confidence: "moyenne" },
  { scope: "bank", name: "Vinaigre (vin / cidre)", eurPerKg: 5.5, confidence: "faible" },
  { scope: "bank", name: "Vinaigrette", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "sauce maison (huile et jus de poulet)", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "saumon rose du Pacifique au naturel", eurPerKg: 30.36, confidence: "moyenne" },
  { scope: "bank", name: "sandwich libanais chich taouk (sauce ail, houmous, salade, cornichons, persil, tomate)", eurPerKg: 11.0, confidence: "faible" },
  { scope: "bank", name: "sandwich libanais shawarma poulet (sauce ail, houmous, salade, cornichons, persil, tomate)", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "sandwich libanais shawarma viande (b\u0153uf/agneau, sauce ail, houmous, salade, cornichons, persil, tomate)", eurPerKg: 13.0, confidence: "faible" },
  { scope: "bank", name: "g\u00e2teau au chocolat noir", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "tarte pizza maison charg\u00e9e (\u0153ufs, lardons, l\u00e9gumes, sauce tomate)", eurPerKg: 9.0, confidence: "faible" },
  { scope: "bank", name: "sardines grill\u00e9es", eurPerKg: 18.0, confidence: "faible" },
  { scope: "bank", name: "filet de limande", eurPerKg: 18.48, confidence: "faible" },
  { scope: "bank", name: "Chicken McNuggets", eurPerKg: 25.0, confidence: "faible" },
  { scope: "bank", name: "sauce Big Mac", eurPerKg: 7.0, confidence: "faible" },
  { scope: "bank", name: "sauce barbecue", eurPerKg: 4.37, confidence: "moyenne" },
  { scope: "bank", name: "McChicken", eurPerKg: 26.0, confidence: "faible" },
  { scope: "bank", name: "tapenade", eurPerKg: 13.63, confidence: "moyenne" },
  { scope: "bank", name: "glace Magnum Almond", eurPerKg: 9.73, confidence: "moyenne" },
  { scope: "bank", name: "pav\u00e9 de saumon \u00e0 la moutarde", eurPerKg: 20.0, confidence: "faible" },
  { scope: "bank", name: "nugget de poulet", eurPerKg: 7.1, confidence: "moyenne" },
  { scope: "bank", name: "chips de patate douce", eurPerKg: 10.0, confidence: "faible" },
  { scope: "bank", name: "glace Magnum Classic", eurPerKg: 9.7, confidence: "faible" },
  { scope: "bank", name: "sauce tomate", eurPerKg: 2.63, confidence: "moyenne" },
  { scope: "bank", name: "escalope de poulet surgel\u00e9e", eurPerKg: 19.98, confidence: "faible" },
  { scope: "bank", name: "pizza aux anchois", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "sauce piment\u00e9e", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "p\u00e2tes orecchiette \u00e0 la sauce tomate", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "c\u00f4te de veau \u00e0 la milanaise pan\u00e9e", eurPerKg: 24.0, confidence: "faible" },
  { scope: "bank", name: "artichaut", eurPerKg: 6.67, confidence: "faible" },
  { scope: "bank", name: "truite fum\u00e9e", eurPerKg: 33.0, confidence: "faible" },
  { scope: "bank", name: "sauce moutarde huile d'olive", eurPerKg: 8.0, confidence: "moyenne" },
  { scope: "bank", name: "caf\u00e9", eurPerKg: 18.72, confidence: "moyenne" },
  { scope: "bank", name: "glace noix de coco", eurPerKg: 8.0, confidence: "faible" },
  { scope: "bank", name: "cr\u00e8me fouett\u00e9e", eurPerKg: 10.88, confidence: "moyenne" },
  { scope: "bank", name: "burger", eurPerKg: 18.0, confidence: "faible" },
  { scope: "bank", name: "omelette aux oignons", eurPerKg: 6.0, confidence: "faible" },
  { scope: "bank", name: "ratatouille", eurPerKg: 4.19, confidence: "moyenne" },
  { scope: "bank", name: "escalope de poulet pan\u00e9e", eurPerKg: 16.0, confidence: "faible" },
  { scope: "bank", name: "l\u00e9gumes", eurPerKg: 4.0, confidence: "faible" },
  { scope: "bank", name: "frites de patate douce", eurPerKg: 5.8, confidence: "moyenne" },
  { scope: "bank", name: "fondant au chocolat", eurPerKg: 15.0, confidence: "faible" },
  { scope: "bank", name: "chantilly", eurPerKg: 10.88, confidence: "faible" },
  { scope: "bank", name: "petites c\u00f4tes d'agneau grill\u00e9es", eurPerKg: 30.0, confidence: "faible" },
  { scope: "bank", name: "brick \u00e0 la viande hach\u00e9e", eurPerKg: 15.0, confidence: "faible" },
  { scope: "bank", name: "brick au thon", eurPerKg: 15.0, confidence: "faible" },
  { scope: "bank", name: "tarte \u00e0 la tomate", eurPerKg: 8.0, confidence: "faible" },
  { scope: "bank", name: "cornet de glace 2 boules", eurPerKg: 40.0, confidence: "faible" },
  { scope: "bank", name: "guacamole maison", eurPerKg: 12.0, confidence: "faible" },
  { scope: "bank", name: "chorizo", eurPerKg: 9.25, confidence: "moyenne" },
  { scope: "bank", name: "viande s\u00e9ch\u00e9e", eurPerKg: 45.0, confidence: "faible" },
  { scope: "bank", name: "sauce a\u00efoli", eurPerKg: 5.89, confidence: "moyenne" },
  { scope: "bank", name: "steak de b\u0153uf grill\u00e9", eurPerKg: 35.0, confidence: "faible" },
  { scope: "bank", name: "baguette poulet tandoori", eurPerKg: 20.0, confidence: "faible" },
  { scope: "bank", name: "chocolat au lait noisettes", eurPerKg: 25.81, confidence: "moyenne" },
  { scope: "bank", name: "l\u00e9gumes po\u00eal\u00e9s", eurPerKg: 5.0, confidence: "faible" },
  { scope: "bank", name: "sardines \u00e0 l'huile", eurPerKg: 13.38, confidence: "moyenne" },
  { scope: "bank", name: "inuline", eurPerKg: 18.0, confidence: "faible" },
  { scope: "bank", name: "moutarde", eurPerKg: 2.05, confidence: "forte" },
  { scope: "bank", name: "vinaigre", eurPerKg: 2.0, confidence: "faible" },
  { scope: "bank", name: "sauce", eurPerKg: 6.0, confidence: "faible" },
  { scope: "catalogue", name: "Pomme", eurPerKg: 2.99, confidence: "moyenne" },
  { scope: "catalogue", name: "Poire", eurPerKg: 3.2, confidence: "faible" },
  { scope: "catalogue", name: "Nectarine", eurPerKg: 4.5, confidence: "faible" },
  { scope: "catalogue", name: "Cl\u00e9mentine", eurPerKg: 3.5, confidence: "faible" },
  { scope: "catalogue", name: "Myrtille", eurPerKg: 15.5, confidence: "faible" },
  { scope: "catalogue", name: "Ananas", eurPerKg: 3.99, confidence: "faible" },
  { scope: "catalogue", name: "Citron", eurPerKg: 2.5, confidence: "faible" },
  { scope: "catalogue", name: "Figue", eurPerKg: 8.0, confidence: "faible" },
  { scope: "catalogue", name: "Datte", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Grenade", eurPerKg: 5.0, confidence: "faible" },
  { scope: "catalogue", name: "Compote de pomme", eurPerKg: 2.5, confidence: "faible" },
  { scope: "catalogue", name: "\u00c9pinards (cuits)", eurPerKg: 3.4, confidence: "moyenne" },
  { scope: "catalogue", name: "Champignons de Paris", eurPerKg: 6.0, confidence: "faible" },
  { scope: "catalogue", name: "Chou-fleur (cuit)", eurPerKg: 2.75, confidence: "moyenne" },
  { scope: "catalogue", name: "Petits pois & carottes (bo\u00eete)", eurPerKg: 4.77, confidence: "moyenne" },
  { scope: "catalogue", name: "Riz complet (cuit)", eurPerKg: 1.3, confidence: "faible" },
  { scope: "catalogue", name: "P\u00e2tes compl\u00e8tes (cuites)", eurPerKg: 1.1, confidence: "faible" },
  { scope: "catalogue", name: "Quinoa (cuit)", eurPerKg: 2.8, confidence: "faible" },
  { scope: "catalogue", name: "Flocons d'avoine", eurPerKg: 1.8, confidence: "moyenne" },
  { scope: "catalogue", name: "Lentilles en bo\u00eete (\u00e9goutt\u00e9es)", eurPerKg: 3.34, confidence: "moyenne" },
  { scope: "catalogue", name: "Haricots blancs (bo\u00eete)", eurPerKg: 3.2, confidence: "faible" },
  { scope: "catalogue", name: "Pois chiches (cuits)", eurPerKg: 2.83, confidence: "moyenne" },
  { scope: "catalogue", name: "Haricots rouges (cuits)", eurPerKg: 3.5, confidence: "faible" },
  { scope: "catalogue", name: "Tofu ferme (nature)", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Tofu soyeux", eurPerKg: 7.0, confidence: "faible" },
  { scope: "catalogue", name: "Seitan", eurPerKg: 17.0, confidence: "faible" },
  { scope: "catalogue", name: "Tempeh", eurPerKg: 16.0, confidence: "faible" },
  { scope: "catalogue", name: "Bavette de b\u0153uf (cuite)", eurPerKg: 37.0, confidence: "faible" },
  { scope: "catalogue", name: "Rumsteck de b\u0153uf (cuit)", eurPerKg: 35.0, confidence: "faible" },
  { scope: "catalogue", name: "Escalope de dinde (cuite)", eurPerKg: 19.0, confidence: "faible" },
  { scope: "catalogue", name: "C\u00f4te de porc (cuite)", eurPerKg: 10.5, confidence: "faible" },
  { scope: "catalogue", name: "Filet mignon de porc (cuit)", eurPerKg: 18.6, confidence: "faible" },
  { scope: "catalogue", name: "Gigot d'agneau (cuit)", eurPerKg: 32.0, confidence: "faible" },
  { scope: "catalogue", name: "Saucisse de Toulouse (cuite)", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Merguez (cuite)", eurPerKg: 14.0, confidence: "faible" },
  { scope: "catalogue", name: "Saumon fum\u00e9", eurPerKg: 35.0, confidence: "faible" },
  { scope: "catalogue", name: "Maquereau (filet)", eurPerKg: 14.0, confidence: "moyenne" },
  { scope: "catalogue", name: "Cabillaud (cuit)", eurPerKg: 30.0, confidence: "faible" },
  { scope: "catalogue", name: "Crevettes (cuites)", eurPerKg: 28.0, confidence: "faible" },
  { scope: "catalogue", name: "Yaourt nature", eurPerKg: 1.9, confidence: "moyenne" },
  { scope: "catalogue", name: "Yaourt \u00e0 la grecque", eurPerKg: 2.15, confidence: "moyenne" },
  { scope: "catalogue", name: "Lait demi-\u00e9cr\u00e9m\u00e9", eurPerKg: 1.53, confidence: "moyenne" },
  { scope: "catalogue", name: "Lait entier", eurPerKg: 1.06, confidence: "moyenne" },
  { scope: "catalogue", name: "Camembert", eurPerKg: 7.52, confidence: "moyenne" },
  { scope: "catalogue", name: "Parmesan", eurPerKg: 24.5, confidence: "moyenne" },
  { scope: "catalogue", name: "Chocolat blanc", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "P\u00e2te \u00e0 tartiner chocolat-noisette", eurPerKg: 8.0, confidence: "moyenne" },
  { scope: "catalogue", name: "Chocolat en poudre (sucr\u00e9)", eurPerKg: 4.0, confidence: "moyenne" },
  { scope: "catalogue", name: "Biscuits petit-beurre", eurPerKg: 3.5, confidence: "faible" },
  { scope: "catalogue", name: "Cookie", eurPerKg: 8.0, confidence: "faible" },
  { scope: "catalogue", name: "Croissant", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Pain au chocolat", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Madeleine", eurPerKg: 8.0, confidence: "faible" },
  { scope: "catalogue", name: "Miel", eurPerKg: 6.0, confidence: "faible" },
  { scope: "catalogue", name: "Confiture", eurPerKg: 4.0, confidence: "faible" },
  { scope: "catalogue", name: "Cr\u00e8me fra\u00eeche 30%", eurPerKg: 4.0, confidence: "moyenne" },
  { scope: "catalogue", name: "Huile de colza", eurPerKg: 2.5, confidence: "faible" },
  { scope: "catalogue", name: "Noix", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Graines de lin", eurPerKg: 13.64, confidence: "moyenne" },
  { scope: "catalogue", name: "Graines de chia", eurPerKg: 12.0, confidence: "faible" },
  { scope: "catalogue", name: "Beurre de cacahu\u00e8te", eurPerKg: 7.0, confidence: "faible" },
  { scope: "catalogue", name: "Coca-Cola", eurPerKg: 1.24, confidence: "moyenne" },
  { scope: "catalogue", name: "Bi\u00e8re", eurPerKg: 2.0, confidence: "faible" },
  { scope: "catalogue", name: "Poivre noir", eurPerKg: 30.0, confidence: "faible" },
  { scope: "catalogue", name: "Fibres (compl\u00e9ment)", eurPerKg: 18.0, confidence: "faible" },
  { scope: "catalogue", name: "Spiruline (poudre)", eurPerKg: 30.0, confidence: "faible" },
  { scope: "catalogue", name: "Levure malt\u00e9e / de bi\u00e8re", eurPerKg: 20.0, confidence: "faible" },
  { scope: "catalogue", name: "Zinc (compl\u00e9ment)", eurPerKg: 250.0, confidence: "faible" },
  { scope: "catalogue", name: "Vitamine D3 (compl\u00e9ment)", eurPerKg: 500.0, confidence: "faible" },
  { scope: "catalogue", name: "Vitamine B12 (compl\u00e9ment)", eurPerKg: 400.0, confidence: "faible" },
  { scope: "catalogue", name: "Vitamine K2 (MK-7, compl\u00e9ment)", eurPerKg: 500.0, confidence: "faible" },
  { scope: "catalogue", name: "Mayonnaise", eurPerKg: 6.84, confidence: "moyenne" },
];
